export const products = [
    {
      id: 1,
      tag: "New Arrival",
      tagColor: "#aced1a",
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "100",
      stars: 5,
      reviews: "1203",
    },
    {
      id: 2,
      tag: "Hot",
      image: "https://readymadeui.com/images/laptop2.webp",
      name: "Lipstck Set",
      price: "350",
      stars: 2,
      reviews: "64",
    },
    {
      id: 3,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: "PS 5 Slim Disc Edition",
      price: "90",
      stars: 5,
      reviews: "11,236",
      originalPrice: "500",
    },
    {
      id: 4,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: "iPhone 15",
      price: "15",
      stars: 4,
      reviews: "2,738",
    },
    {
      id: 5,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " Ziva Purse",
      price: "58",
      stars: 1,
      tag: "25% OFF",
      reviews: "42",
      originalPrice: "73",
    },
    {
      id: 6,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "325",
      stars: 3,
      reviews: "2",
    },
    {
      id: 7,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 8,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 9,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 10,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 11,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id:12,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 13,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 14,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 15,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 16,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 17,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 18,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 19,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 20,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 21,
      tag: "New Arrival",
      tagColor: "#aced1a",
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "200",
      stars: 5,
      reviews: "1203",
    },
    {
      id: 22,
      tag: "Hot",
      image: "https://readymadeui.com/images/laptop2.webp",
      name: "Lipstck Set",
      price: "350",
      stars: 2,
      reviews: "64",
    },
    {
      id: 23,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: "PS 5 Slim Disc Edition",
      price: "90",
      stars: 5,
      reviews: "11,236",
      originalPrice: "500",
    },
    {
      id: 24,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: "iPhone 15",
      price: "15",
      stars: 4,
      reviews: "2,738",
    },
    {
      id: 25,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " Ziva Purse",
      price: "58",
      stars: 1,
      tag: "25% OFF",
      reviews: "42",
      originalPrice: "73",
    },
    {
      id: 26,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "325",
      stars: 3,
      reviews: "2",
    },
    {
      id: 27,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 28,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 29,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 30,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 31,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id:32,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 33,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 34,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 35,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 36,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 37,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 38,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 39,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 40,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 41,
      tag: "New Arrival",
      tagColor: "#aced1a",
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "400",
      stars: 5,
      reviews: "1203",
    },
    {
      id: 42,
      tag: "Hot",
      image: "https://readymadeui.com/images/laptop2.webp",
      name: "Lipstck Set",
      price: "350",
      stars: 2,
      reviews: "64",
    },
    {
      id: 43,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: "PS 5 Slim Disc Edition",
      price: "90",
      stars: 5,
      reviews: "11,236",
      originalPrice: "500",
    },
    {
      id: 44,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: "iPhone 15",
      price: "15",
      stars: 4,
      reviews: "2,738",
    },
    {
      id: 45,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " Ziva Purse",
      price: "58",
      stars: 1,
      tag: "25% OFF",
      reviews: "42",
      originalPrice: "73",
    },
    {
      id: 46,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "325",
      stars: 3,
      reviews: "2",
    },
    {
      id: 47,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 48,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 49,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 50,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 51,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id:52,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 53,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 54,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 55,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 56,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 57,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 58,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 59,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 60,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 61,
      tag: "New Arrival",
      tagColor: "#aced1a",
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "600",
      stars: 5,
      reviews: "1203",
    },
    {
      id: 62,
      tag: "Hot",
      image: "https://readymadeui.com/images/laptop2.webp",
      name: "Lipstck Set",
      price: "350",
      stars: 2,
      reviews: "64",
    },
    {
      id: 63,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: "PS 5 Slim Disc Edition",
      price: "90",
      stars: 5,
      reviews: "11,236",
      originalPrice: "500",
    },
    {
      id: 64,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: "iPhone 15",
      price: "15",
      stars: 4,
      reviews: "2,738",
    },
    {
      id: 65,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " Ziva Purse",
      price: "58",
      stars: 1,
      tag: "25% OFF",
      reviews: "42",
      originalPrice: "73",
    },
    {
      id: 66,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "325",
      stars: 3,
      reviews: "2",
    },
    {
      id: 67,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 68,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 69,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 70,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 71,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id:72,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 73,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 74,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 75,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 76,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 77,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 78,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 79,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    {
      id: 80,
      image: "https://readymadeui.com/images/laptop2.webp",
      name: " HP Polycarbonate Laptop 15S, AMD, 15.6-IInch (39.6 Cm)",
      price: "136",
      stars: 5,
      reviews: "755",
    },
    
  ];